// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfs9JVwnn42eUG2DujFH7dVVr0xzCkUog',
    appId: '1:619837532652:web:1f3e9c0193b8a72f16b8c9',
    messagingSenderId: '619837532652',
    projectId: 'fooddeliveryapp-426e3',
    authDomain: 'fooddeliveryapp-426e3.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-426e3.appspot.com',
    measurementId: 'G-XSK9Y54KND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ606KRM1B1xgotmY2MOpyjNd2hx9Y3jg',
    appId: '1:619837532652:android:acbdde10c153f24916b8c9',
    messagingSenderId: '619837532652',
    projectId: 'fooddeliveryapp-426e3',
    storageBucket: 'fooddeliveryapp-426e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNi85Z6vSMXnZO7jyNQyjI8PsNpi68rR0',
    appId: '1:619837532652:ios:56b7dfde3f79645e16b8c9',
    messagingSenderId: '619837532652',
    projectId: 'fooddeliveryapp-426e3',
    storageBucket: 'fooddeliveryapp-426e3.appspot.com',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNi85Z6vSMXnZO7jyNQyjI8PsNpi68rR0',
    appId: '1:619837532652:ios:56b7dfde3f79645e16b8c9',
    messagingSenderId: '619837532652',
    projectId: 'fooddeliveryapp-426e3',
    storageBucket: 'fooddeliveryapp-426e3.appspot.com',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfs9JVwnn42eUG2DujFH7dVVr0xzCkUog',
    appId: '1:619837532652:web:3b051f350d0593f516b8c9',
    messagingSenderId: '619837532652',
    projectId: 'fooddeliveryapp-426e3',
    authDomain: 'fooddeliveryapp-426e3.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-426e3.appspot.com',
    measurementId: 'G-XBXD8XRCG4',
  );

}